In [1]:
#################################################
#  Company    : Stevens Institute of Technology
#  Project    : HW03
#  Purpose    : To perform the classification model given the knn methodology given the database called breast-cancer-wisconsin.data.csv
#  First Name : Spruha
#  Last Name  : Paradkar
#  Id		  : 10470967
#  Date       : 10/09/2023
#  Comments   : I pledge my honor that I have abided by the Stevens Honor System
#################################################

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [3]:
print('Loading the breast cancer dataset')
breastCancer = pd.read_csv('/Users/spruhap/Downloads/breast-cancer-wisconsin.csv')
breastCancer.head(10)

Loading the breast cancer dataset

    Sample  F1  F2  F3  F4  F5  F6  F7  F8  F9  Class
0  1000025   5   1   1   1   2   1   3   1   1      2
1  1002945   5   4   4   5   7  10   3   2   1      2
2  1015425   3   1   1   1   2   2   3   1   1      2
3  1016277   6   8   8   1   3   4   3   7   1      2
4  1017023   4   1   1   3   2   1   3   1   1      2
5  1017122   8  10  10   8   7  10   9   7   1      4
6  1018099   1   1   1   1   2  10   3   1   1      2
7  1018561   2   1   2   1   2   1   3   1   1      2
8  1033078   2   1   1   1   2   1   1   1   5      2
9  1033078   4   2   1   1   2   1   2   1   1      2

In [4]:
print('The length of the database before dropping all the missing values')
print(len(breastCancer))

The length of the database before dropping all the missing values
699

In [5]:
breastCancer = breastCancer.drop(breastCancer.loc[breastCancer['F6']== '?'].index)
print('The length of the database after dropping all the missing values')
print(len(breastCancer))

The length of the database after dropping all the missing values
683

In [6]:
print('Dropping the Class field')
# Splitting the dataset
attributes = breastCancer.drop(columns = ['Class', 'Sample'])
attributes.head(10)

Dropping the Class field

   F1  F2  F3  F4  F5  F6  F7  F8  F9
0   5   1   1   1   2   1   3   1   1
1   5   4   4   5   7  10   3   2   1
2   3   1   1   1   2   2   3   1   1
3   6   8   8   1   3   4   3   7   1
4   4   1   1   3   2   1   3   1   1
5   8  10  10   8   7  10   9   7   1
6   1   1   1   1   2  10   3   1   1
7   2   1   2   1   2   1   3   1   1
8   2   1   1   1   2   1   1   1   5
9   4   2   1   1   2   1   2   1   1

In [7]:
print('Creating a data frame called target for the Class variable')
target = breastCancer['Class'] # target variable
target.head(10)

Creating a data frame called target for the Class variable

0    2
1    2
2    2
3    2
4    2
5    4
6    2
7    2
8    2
9    2
Name: Class, dtype: int64

In [8]:
#RANDOM_STATE helps to keep the data consistent -> it keeps the values consistent when you run the code again
print('Dividing the data into test and train data given the 30/70 split ratio')
attribute_train, attribute_test, target_train,target_test  = train_test_split(attributes, target,test_size = 0.3, random_state = 87, shuffle = True)

Dividing the data into test and train data given the 30/70 split ratio

k = 3

In [9]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# k_values = [3, 5, 10]
print('Doing the classification for k = 3')
print()
k = 3

#creates a default model with the no of neighbors you want
knn = KNeighborsClassifier(n_neighbors = k)

#this fits the data -> actually runs the classifier and fits the data actually
knn.fit(attribute_train, target_train)

#prediciting given the values from f1-f9 what the class should be
target_pred = knn.predict(attribute_test)

cm=confusion_matrix(target_test, target_pred)
print('Confusion Matrix for k = 3')
print(confusion_matrix(target_test, target_pred))
print()

print('Accuracy score for k = 3')
print(accuracy_score(target_test, target_pred))
print()

print('Classification Report for k = 3')
print(classification_report(target_test, target_pred))

Doing the classification for k = 3

Confusion Matrix for k = 3
[[126   1]
 [  5  73]]

Accuracy score for k = 3
0.9707317073170731

Classification Report for k = 3
              precision    recall  f1-score   support

           2       0.96      0.99      0.98       127
           4       0.99      0.94      0.96        78

    accuracy                           0.97       205
   macro avg       0.97      0.96      0.97       205
weighted avg       0.97      0.97      0.97       205

k = 5

In [10]:
print('Doing the classification for k = 5')
print()
k = 5

#creates a default model with the no of neighbors you want
knn = KNeighborsClassifier(n_neighbors = k)

#this fits the data -> actually runs the classifier and fits the data actually
knn.fit(attribute_train, target_train)

#prediciting given the values from f1-f9 what the class should be
target_pred = knn.predict(attribute_test)

cm=confusion_matrix(target_test, target_pred)
print('Confusion Matrix for k = 5')
print(confusion_matrix(target_test, target_pred))
print()

print('Accuracy score for k = 5')
print(accuracy_score(target_test, target_pred))
print()

print('Classification Report for k = 5')
print(classification_report(target_test, target_pred))

Doing the classification for k = 5

Confusion Matrix for k = 5
[[125   2]
 [  5  73]]

Accuracy score for k = 5
0.9658536585365853

Classification Report for k = 5
              precision    recall  f1-score   support

           2       0.96      0.98      0.97       127
           4       0.97      0.94      0.95        78

    accuracy                           0.97       205
   macro avg       0.97      0.96      0.96       205
weighted avg       0.97      0.97      0.97       205

k = 10

In [11]:
print('Doing the classification for k = 10')
print()
k = 10

#creates a default model with the no of neighbors you want
knn = KNeighborsClassifier(n_neighbors = k)

#this fits the data -> actually runs the classifier and fits the data actually
knn.fit(attribute_train, target_train)

#prediciting given the values from f1-f9 what the class should be
target_pred = knn.predict(attribute_test)

cm=confusion_matrix(target_test, target_pred)
print('Confusion Matrix for k = 10')
print(confusion_matrix(target_test, target_pred))
print()

print('Accuracy score for k = 10')
print(accuracy_score(target_test, target_pred))
print()

print('Classification Report for k = 10')
print(classification_report(target_test, target_pred))

Doing the classification for k = 10

Confusion Matrix for k = 10
[[125   2]
 [  7  71]]

Accuracy score for k = 10
0.9560975609756097

Classification Report for k = 10
              precision    recall  f1-score   support

           2       0.95      0.98      0.97       127
           4       0.97      0.91      0.94        78

    accuracy                           0.96       205
   macro avg       0.96      0.95      0.95       205
weighted avg       0.96      0.96      0.96       205